-- ------------------------------- 9/1/25 --------------------------------

DELIMITER //
CREATE FUNCTION F_MAXSAL( P_DEPT INT)
RETURNS DECIMAL
DETERMINISTIC
BEGIN
DECLARE V_MAXSAL DECIMAL;
SELECT MAX(SAL) INTO V_MAXSAL
FROM EMP
WHERE DEPTNO=P_DEPT;
RETURN (V_MAXSAL);
END //
DELIMITER ;

SELECT F_MAXSAL(10);



DELIMITER //
CREATE FUNCTION F_DEPTNO( P_SAL INT)
RETURNS DECIMAL
DETERMINISTIC
BEGIN
DECLARE V_DEPTNO DECIMAL;
SELECT DEPTNO INTO V_DEPTNO
FROM EMP
WHERE SAL=P_SAL;
RETURN (V_DEPTNO);
END //
DELIMITER ;
CALL S_P_4(@P_SAL);
SELECT F_DEPTNO(@P_SAL);


-- DESCISION MAKING
-- IF THEN 
DELIMITER //
CREATE FUNCTION F_IF( P_SAL INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE SALARY_STAT VARCHAR(50);
IF P_SAL >3000 THEN SET SALARY_STAT='HIGH ERANING';
END IF;
RETURN SALARY_STAT;
END //
DELIMITER ;

CALL S_P_5(10,@P_SAL);
SELECT F_IF(@P_SAL);


-- IF THEN ELSE
DELIMITER //
CREATE FUNCTION F_IF_ELSE( P_SAL INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE SALARY_STAT VARCHAR(50);
IF P_SAL >3000 THEN SET SALARY_STAT='HIGH ERANING';
ELSE SET SALARY_STAT='LOW EARNING';
END IF;
RETURN SALARY_STAT;
END //
DELIMITER ;
CALL S_P_5(10,@P_SAL);
SELECT F_IF_ELSE(@P_SAL);

-- IF THEN ELSEIF ELSE
DELIMITER //
CREATE FUNCTION F_IF_ELSEIF( P_SAL INT)
RETURNS VARCHAR(50)
DETERMINISTIC
BEGIN
DECLARE SALARY_STAT VARCHAR(50);
IF P_SAL >3000 THEN SET SALARY_STAT='HIGH ERANING';
ELSEIF P_SAL<=3000 and P_SAL>2000 THEN SET SALARY_STAT='AVERAGE EARNING';
ELSE SET SALARY_STAT='LOW EARNING';
END IF;
RETURN SALARY_STAT;
END //
DELIMITER ;
CALL S_P_5(10,@P_SAL);
SELECT F_IF_ELSEIF(@P_SAL);

-- CASE STATEMENTS
SELECT *, 
CASE
WHEN SAL>3000 THEN "HIGH EARNING"
WHEN SAL>2000 THEN "AVERAGE EARNING"
ELSE "LOW EARNING" 
END AS SALARY_STAT
FROM EMP;












